//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : STHF
//  @ File Name : Controller.java
//  @ Date : 2023. 04. 15.
//  @ Author : 
//
//
package controller;
import container.*;
import java.util.ArrayList;
public class Controller {
	public Pump getRandomUndamagedPump(ArrayList<Pump> pumps) {
	}
	
	public void damagePump(ArrayList<Pump> pumps)
	{
	 	for(Pump p:pumps)
		{
			if(turnCount==p.getRandomDamageValue())
			{
				p.setisDamaged(true);
			}
		}
	}
	
	public void waterFlow()
	{

	}
}
