//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : STHF
//  @ File Name : Controller.java
//  @ Date : 2023. 04. 15.
//  @ Author : 
//
//
package controller;
import container.*;
import map.Map;

public class Controller {

	public void damagePump() {
		for(Container c : Map.getContainers()){
			c.lifeCycle();
		}
	}

	public void waterFlow() {

	}
}
